modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Connor-Harkness/Smokecraft/issues"

[[mods]]
modId="smokecraft"
version="${file.jarVersion}"
displayName="Smokecraft"
description='''
A Minecraft mod that adds cigarettes, lighters, and smoking mechanics. Features configurable effects (cosmetic-only by default), particle effects, and sound. Always smoke responsibly - this is just a game mod!
'''
authors="SmokecraftTeam"
credits="NeoForge team for the excellent modding framework"
logoFile="logo.png"

[[dependencies.smokecraft]]
modId="neoforge"
mandatory=true
versionRange="[21.1.85,)"
ordering="NONE"
side="BOTH"

[[dependencies.smokecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"